services:
  backend:
    build: ./music-app-backend
    ports:
      - "8000:8000"
    env_file:
      - ./music-app-backend/.env
    volumes:
      - backend_db:/app/db
    command: >
     sh -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
       gunicorn app.wsgi:application --bind 0.0.0.0:8000"


  frontend:
    build:
      context: ./music-app-frontend
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:8000"
        NEXT_PUBLIC_GRAPHQL_ENDPOINT: "/graphql/"
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  backend_db:
